### ISSUE TITLE
Enable HTTPS endpoint for staging server

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/dice-server#18]
The MARTI staging server configuration currently only enables the HTTP endpoint.  To be at parity with the production server, the HTTPS endpoint should also be enabled.

Tasks:

* [x] Enable HTTPS endpoint in Nginx configuration.
* [x] Update staging server registration link in TripleA client (_/dice\_servers/dice-staging.tripleawarclub.org_) to use HTTPS.

**Comment by ssoloff** [comment]
@RoiEXLab I'm pretty sure I asked this before, but what is required before I can update the Nginx configuration?  Do we need to get a new certificate for the `dice-staging.tripleawarclub.org` subdomain?  Or can the existing certificate under _/etc/letsencrypt/live/tripleawarclub.org_ be updated to include the additional subdomain?

**Comment by RoiEXLab** [comment]
@ssoloff The existing certificate can be updated, I believe I already updated it when I created the dice-staging DNS entry.
You can check by running the certbot tool and listing all active certificates.
I don't know the exact command, but `--help` should give a pretty good explanation.

**Comment by RoiEXLab** [comment]
@ssoloff I just checked. The certificate is already active for `dice-staging.tripleawarclub.org`, so the only thing that needs to be done is to update the config

**Comment by ssoloff** [comment]
Excellent!  Thanks for checking, @RoiEXLab.

**Comment by ssoloff** [comment]
🎉 I applied the staging configuration from #28 and confirmed all MARTI operations (registration, email validation, dice roll, dice roll validation, and unsubscribe) work over HTTPS.  Task (1) is now complete.

**Comment by ssoloff** [comment]
Task (2) is complete via triplea-game/triplea#2819.
