### ISSUE TITLE
Consider enabling only HTTPS endpoint

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/dice-server#19]
A few months ago, we disabled the HTTP endpoint for the MARTI production server so that users were forced to use the HTTPS endpoint.  (Actually, we redirected the HTTP endpoint to the HTTPS endpoint, but the effect is the same.)  At that time, some users reported they could no longer use MARTI.  The root cause was determined to be the general TLS certificate validation problem that had been reported multiple times during that same period.

It has been proposed that we revisit this topic since we haven't seen the TLS certificate validation problem reported lately.  We have a few options here in addition to HTTPS-only:

1. Leave things as they are today.  Enable both HTTP and HTTPS endpoints.  The TripleA client will continue to use the HTTP endpoints, but users are free to use the HTTPS endpoints from their browser for tasks like registration, registration validation, dice roll validation, etc.
1. Redirect HTTP endpoints to HTTPS endpoints.  This effectively disables the HTTP endpoints so that access from a TripleA client or browser will use HTTPS.  If a user can't connect to the HTTPS endpoint for some reason, they will be unable to use MARTI.
1. Similar to (1) in that both HTTP and HTTPS endpoints would be enabled.  However, we would add two entries per server to the TripleA client: one for HTTP and one for HTTPS with the HTTPS entry having a higher precedence in the list.  That would allow users who may still experience the TLS certificate validation problem to fallback to the HTTP endpoint.  I expect the resulting dice server list in the TripleA client would contain entries for each server like:
    ```
    dice.tripleawarclub.org (secure)
    dice.tripleawarclub.org
    ```
    Or alternately:
    ```
    dice.tripleawarclub.org
    dice.tripleawarclub.org (INSECURE)
    ```
1. Similar to (3) except we only have a single entry for each server and do the HTTPS-to-HTTP fallback in code.  This could make the code a bit messy just to support an issue that doesn't affect that many users.

Thoughts?

**Comment by RoiEXLab** [comment]
@ssoloff Actually the problem with the dice server was me not correctly setting up the redirect for HTTP. So users were not being redirected to the MARTI software, but another configured webroot instead

(You can simulate this behaviour currently when visiting https://dice-staging.tripleawarclub.org although nowhere in the nginx config we accept connections for this https endpoint, we get to see tripleawarclub.org instead although we should really see nothing)
So we technically never ran into any issues with let's encrypt certificates except for that [one time](https://github.com/triplea-game/triplea/issues/2554) where reinstalling java fixed the issue.

**Comment by ssoloff** [comment]
@RoiEXLab Thanks for the clarification.  However, as we discussed in Gitter, there is still another failure mode involving the use of a TLS proxy as documented in triplea-game/triplea#2472.  We never completely resolved that issue due to lack of activity (although it seems like installing the proxy's certificate in the Java truststore should have fixed it).

In summary, if we go HTTPS-only and a user reports a TLS certificate validation error, we can propose to them:

1. Upgrade to the latest Java 8 JRE to get a truststore with the latest root CAs.
1. Otherwise, determine if they are behind a TLS proxy and ask them to install the proxy's certificate in the truststore (unconfirmed).

If that's an acceptable process, then I can't think of anything else preventing us from going HTTPS-only.

**Comment by RoiEXLab** [comment]
I'd be fine with this process.
Tagging @ron-murhammer and @DanVanAtta for their opinion on this.

**Comment by ssoloff** [comment]
One thing I noted after promoting MARTI 2.0.0 into production...  The links contained in dice roll emails now use HTTP instead of HTTPS.  This change is due to the following:

1. The TripleA client uses HTTP to submit requests to MARTI.
1. The old MARTI code hard-coded the base URL used in emails with the HTTPS scheme.  The new MARTI code removed the hard-coded URL in order to allow testing of MARTI in other contexts (e.g. in the MARTI Docker image).  The new code derives all links from the base URL used in the request.

This isn't a huge deal because we redirect all HTTP connections to HTTPS, but I just wanted to document it in case people start noticing it.  If we switch to an HTTPS-only endpoint, as this issue proposes, the URLs will revert back to HTTPS.

**Comment by ssoloff** [comment]
@DanVanAtta @ron-murhammer Bumping this discussion now that the staging server has HTTPS enabled.

**Comment by ssoloff** [comment]
Just noting that we have finally been able to [resolve](https://github.com/triplea-game/triplea/issues/2821) the TLS proxy issue originally reported in triplea-game/triplea#2472.  Knowing how to instruct users to fix that problem should further reduce the risk of the HTTPS-only option.

**Comment by ssoloff** [comment]
@DanVanAtta @ron-murhammer Bumping...

**Comment by ssoloff** [comment]
@DanVanAtta @ron-murhammer Bumping...

**Comment by DanVanAtta** [comment]
Oh, I missed this, appropriate bump @ssoloff 

Similar to option 4, it'd be ideal if we could have game client try https, and fall back to http and report it to us. Then we'd know it's not a problem.

Do we expect this to be a problem for some users? Seems we had a number of reports about certs previously, would we get more by going https only? It may be worthwhile even if, but would be good to better know the pro/cons here.

**Comment by ssoloff** [comment]
@DanVanAtta The HTTPS-specific issues users were reporting seemed to have tapered off.  There were two root causes of these problems:

1. Users were using an old JRE that didn't have the latest GitHub CA certs in the truststore.  Upgrading to the latest JRE resolved the problem.
1. Users were using an HTTPS proxy, which didn't install its own certificate into the JRE truststore.  We walked one user through the process of manually installing the proxy certificate, and it worked successfully (triplea-game/triplea#2821).

So if users report HTTPS issues in the future, I think we have a good story to get their HTTPS connections working again.

Assuming the worst case whereby we can't get a user's HTTPS connection working, we have another workaround we can propose to the user: they can simply edit the dice server properties file in the install and switch the protocol back to HTTP.  (This is basically a variant on option (3).)

The fallback option (4) is doable, but will require a code change.  As I mentioned in the description, doing that work for an issue that may only affect a small group of users (for which multiple workarounds are available) might not be the best use of development resources.

**Comment by ssoloff** [comment]
@DanVanAtta @ron-murhammer Bumping...

Highlighting a new option I outlined in my previous comment, let's call it 3(b):

* Enable both HTTP and HTTPS endpoints on MARTI.
* Switch the TripleA client to use the HTTPS endpoint (with only a single entry in the dice server list, as it is today).
* In the unexpected case a user reports an HTTPS-related problem that cannot be resolved as we've done before (e.g. proxy certificates, outdated JREs, etc.), we instruct the user to modify their dice server properties file and switch the connection back to HTTP.

**Comment by DanVanAtta** [comment]
https for dice rolls makes sense. What's the impact of `https` only @ssoloff to users? If we update our error messaging to detect the problem and give specific fixes, would we mitigate that impact? I would also be concerned such a move would add to admin overhead, dealing with bug reports from users where this does not work, or users abandoning. So if the error messaging is "smart", and we don't just vomit a stack trace per usual, I can fully support https here. If on the other hand the benefits are marginal and we'll just make everyone life a bit more complicated, then - is it worth it?

**Comment by ssoloff** [comment]
There are currently six HTTPS-related issues in the tracker:

Issue | Root Cause | Confirmation
:-- | :-- | :--
triplea-game/triplea#2443 | (1) or (2) | Unconfirmed but high confidence
triplea-game/triplea#2468 | (1) or (2) | Unconfirmed but high confidence
triplea-game/triplea#2472 | (2) | Confirmed
triplea-game/triplea#2554 | (1) | Confirmed
triplea-game/triplea#2821 | (2) | Confirmed
triplea-game/triplea#3224 | (3) | Unconfirmed

Where the identified root causes are:

1. Out-of-date GitHub CA certs due to use of an older JRE.  Upgrading to the latest JRE fixed the problem.
1. User has an HTTPS proxy installed.  Importing the proxy's CA certificate into the JRE's _cacerts_ file fixed the problem.
1. User appears to have a corrupt _cacerts_ file.

I believe the last one is an outlier and unlikely to affect users, in general.  Therefore, the other two root causes are what we might have to deal with after switching the dice servers to HTTPS.  Both have well-known solutions.

For affected users, it's unlikely they will encounter the issue when connecting to the dice server.  They are more likely to encounter it first when downloading a map (which is already HTTPS only) because this task naturally precedes playing a game with a dice server.  So I don't think flipping this switch on the dice server is going to result in an increase in HTTPS-related issues because users are going to experience the problem regardless.  (Unless there happens to be a CA issue related to our Let's Encrypt certs, which would be isolated to the dice servers.)

**Comment by DanVanAtta** [comment]
Thank you for a detailed analysis. The point about maps all being https already is very compelling. There is benefit to tell players we do dice rolls over https. In this case I would suggest we do dice rolling as https only, with http only/maybe for debug.

**Comment by ssoloff** [comment]
triplea-game/triplea#3277 enables HTTPS connections to both MARTI servers.

As suggested, we'll leave the HTTP endpoints on `tripleawarclub.org` enabled for now.  We can revisit this topic in the future and disable HTTP completely at that time if we find no value in it.
