### ISSUE TITLE
Using robots.txt

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/dice-server#23]
I just skimmed through the logs and saw a lot of GET requests for a robots.txt file.
My suggestion would be to create those files and disallow everything so the dice server won't appear in the search results.

**Comment by ssoloff** [comment]
@RoiEXLab Could you please submit a PR that adds the required file(s)?  We can then deploy it while QA is testing MARTI staging so it's ready for when we promote that to production.

**Comment by RoiEXLab** [comment]
@ssoloff I wasn't sure if this Repo was ready for PRs yet.
If it's ready to accept PRs, I'd like to revert some of the commits you made to bring this Repo to the state the production server is currently in.
I'll submit a PR.

**Comment by ssoloff** [comment]
> If it's ready to accept PRs, I'd like to revert some of the commits you made to bring this Repo to the state the production server is currently in.

It's not ready for code changes until we promote staging to production.  I figured a _robots.txt_ file is not a code change, but I understand what you're saying.  Maybe we should keep _everything_ on hold until promotion occurs.

Regardless, thanks for the PR.  If we choose not to merge it now, it should have no problem remaining conflict-free for a week or two.

(BTW, the code _does_ match production other than the DB connection info changes and some code to automatically generate the encryption key if it is missing.  That was the purpose of #2.  I believe the code you originally gave me in a zip file was not actually deployed.  Run

```bash
$ git diff /usr/share/nginx/html/dice-staging.tripleawarclub.org/public_html/ /usr/share/nginx/html/dice.tripleawarclub.org/public_html/
```

and you'll see what I'm talking about.)
