### ISSUE TITLE
Dice server license

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/dice-server#40]
When this repo was first created, GPLv3 was selected as the license.  **Was there a historical reason why GPLv3 was chosen?**  For example, did MARTI's original author state someplace that this was the chosen license?

If there is no historical reason for choosing GPLv3, **would [AGPLv3](https://choosealicense.com/licenses/agpl-3.0/) be more appropriate?**  The key benefit of AGPLv3 over GPLv3 is

> When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.

This seems important since MARTI is always expected to run remotely and only provide services over a network.  Using AGPLv3 would prevent someone from running a modified version of MARTI without disclosing the source code.

**Comment by RoiEXLab** [comment]
> Was there a historical reason why GPLv3 was chosen?

@ssoloff I don't think so. I thought off the TripleA repository, where it uses GPLv2, and I thought why not use GPLv3 instead ^^

We can change it as you like, no idea who created the dice server software in the first place, maybe @veqryn does know something?

**Comment by veqryn** [comment]
I believe it was written by some of the original authors of TripleA, long before I joined.

Personally, I prefer `Mozilla Public License 2.0` over the more restrictive GPL's.

**Comment by RoiEXLab** [comment]
I normally license my own software under the MIT license wich is even less restrictive ^^
But I'd be fine either way

**Comment by ssoloff** [comment]
@DanVanAtta @ron-murhammer Any opinions here on the license to use for MARTI?

To reiterate, the reason I opened this issue is because I _assumed_ the "spirit of the TripleA project" was to prevent closed-source use of any code, and the current license (GPLv3) would allow someone to host their own derivative version of MARTI without disclosing the source.  If I misinterpreted that philosophy, then I guess it doesn't really matter which OSS license we choose.

**Comment by ron-murhammer** [comment]
I'd agree that preventing closed-source use is the spirit of TripleA project and prefer to use a license that aligns with that.

**Comment by veqryn** [comment]
I'm fine either way.  If MARTI was written by the original authors of TripleA, it probably would have been licence'd under GPLv2, since that is what TripleA was put under.  If it is ok to upgrade that to AGPLv3, then do it.  If not, then GPLv3 works too.

**Comment by ssoloff** [comment]
Thanks for all the input, everyone.

At this time, the only OSS license I know of that requires disclosure of source for derivative works not actually delivered to an end user is the AGPL.  If anyone knows of a similar license they'd like considered, please feel free to suggest it here.  Otherwise, I'll probably change the license for this repo over the weekend.

**Comment by ron-murhammer** [comment]
Works for me. I'd like to get to a point where we have all of the repos under the same license but that may be challenging...

**Comment by DanVanAtta** [comment]
AGPL seems reasonable, no objections here.
